
package ehealth.controller_pc.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ehealth.controller_db.ws.Goal;
import ehealth.controller_db.ws.HealthMeasureHistory;
import ehealth.controller_db.ws.MeasureDefinition;
import ehealth.controller_db.ws.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicePc", targetNamespace = "http://ws.controller_pc.ehealth/")
@XmlSeeAlso({
    ehealth.controller_db.ws.ObjectFactory.class,
    ehealth.controller_pc.ws.ObjectFactory.class
})
public interface ServicePc {


    /**
     * 
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadPersonListResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readPersonListRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param idPerson
     * @return
     *     returns ehealth.controller_db.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadPersonResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readPersonRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.UpdatePersonResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/updatePersonRequest", output = "http://ws.controller_pc.ehealth/ServicePc/updatePersonResponse")
    public void updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns ehealth.controller_db.ws.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.CreatePersonResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/createPersonRequest", output = "http://ws.controller_pc.ehealth/ServicePc/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.DeletePersonResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/deletePersonRequest", output = "http://ws.controller_pc.ehealth/ServicePc/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param idPerson
     * @param measureType
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.HealthMeasureHistory>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonHistory", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadPersonHistory")
    @ResponseWrapper(localName = "readPersonHistoryResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadPersonHistoryResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readPersonHistoryRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readPersonHistoryResponse")
    public List<HealthMeasureHistory> readPersonHistory(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "measureTypes", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadMeasureTypesResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readMeasureTypesRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readMeasureTypesResponse")
    public List<String> readMeasureTypes();

    /**
     * 
     * @param idPerson
     * @param mid
     * @param measureType
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasure", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadPersonMeasure")
    @ResponseWrapper(localName = "readPersonMeasureResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadPersonMeasureResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readPersonMeasureRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readPersonMeasureResponse")
    public HealthMeasureHistory readPersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "mid", targetNamespace = "")
        Long mid);

    /**
     * 
     * @param idPerson
     * @param measure
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.SavePersonMeasureResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/savePersonMeasureRequest", output = "http://ws.controller_pc.ehealth/ServicePc/savePersonMeasureResponse")
    public HealthMeasureHistory savePersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measure", targetNamespace = "")
        HealthMeasureHistory measure);

    /**
     * 
     * @param idPerson
     * @param measure
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePersonMeasure", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.UpdatePersonMeasure")
    @ResponseWrapper(localName = "updatePersonMeasureResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.UpdatePersonMeasureResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/updatePersonMeasureRequest", output = "http://ws.controller_pc.ehealth/ServicePc/updatePersonMeasureResponse")
    public HealthMeasureHistory updatePersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measure", targetNamespace = "")
        HealthMeasureHistory measure);

    /**
     * 
     * @param measureType
     * @return
     *     returns ehealth.controller_db.ws.MeasureDefinition
     */
    @WebMethod
    @WebResult(name = "measureType", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureType", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadMeasureType")
    @ResponseWrapper(localName = "readMeasureTypeResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadMeasureTypeResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readMeasureTypeRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readMeasureTypeResponse")
    public MeasureDefinition readMeasureType(
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param goal
     * @return
     *     returns ehealth.controller_db.ws.Goal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateGoal", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.UpdateGoal")
    @ResponseWrapper(localName = "updateGoalResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.UpdateGoalResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/updateGoalRequest", output = "http://ws.controller_pc.ehealth/ServicePc/updateGoalResponse")
    public Goal updateGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal);

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "readGoalList", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadGoalList")
    @ResponseWrapper(localName = "readGoalListResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadGoalListResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readGoalListRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readGoalListResponse")
    public List<String> readGoalList(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "readLatestGoalList", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadLatestGoalList")
    @ResponseWrapper(localName = "readLatestGoalListResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadLatestGoalListResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readLatestGoalListRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readLatestGoalListResponse")
    public List<String> readLatestGoalList(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param goal
     * @return
     *     returns ehealth.controller_db.ws.Goal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveGoal", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.SaveGoal")
    @ResponseWrapper(localName = "saveGoalResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.SaveGoalResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/saveGoalRequest", output = "http://ws.controller_pc.ehealth/ServicePc/saveGoalResponse")
    public Goal saveGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal);

    /**
     * 
     * @param idPerson
     * @param before
     * @param after
     * @param measureType
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.HealthMeasureHistory>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureHistoriesByDate", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadMeasureHistoriesByDate")
    @ResponseWrapper(localName = "readMeasureHistoriesByDateResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadMeasureHistoriesByDateResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readMeasureHistoriesByDateRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readMeasureHistoriesByDateResponse")
    public List<HealthMeasureHistory> readMeasureHistoriesByDate(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "before", targetNamespace = "")
        XMLGregorianCalendar before,
        @WebParam(name = "after", targetNamespace = "")
        XMLGregorianCalendar after);

    /**
     * 
     * @param weight
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "bmi", targetNamespace = "")
    @RequestWrapper(localName = "readBmi", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadBmi")
    @ResponseWrapper(localName = "readBmiResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadBmiResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readBmiRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readBmiResponse")
    public String readBmi(
        @WebParam(name = "weight", targetNamespace = "")
        double weight,
        @WebParam(name = "height", targetNamespace = "")
        double height);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "quote", targetNamespace = "")
    @RequestWrapper(localName = "readQuote", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadQuote")
    @ResponseWrapper(localName = "readQuoteResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadQuoteResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readQuoteRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readQuoteResponse")
    public String readQuote();

    /**
     * 
     * @param person
     * @param measureType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "goalStatus", targetNamespace = "")
    @RequestWrapper(localName = "readGoalStatus", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadGoalStatus")
    @ResponseWrapper(localName = "readGoalStatusResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadGoalStatusResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readGoalStatusRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readGoalStatusResponse")
    public String readGoalStatus(
        @WebParam(name = "person", targetNamespace = "")
        Person person,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param person
     * @param days
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "stepStatus", targetNamespace = "")
    @RequestWrapper(localName = "readSteps", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadSteps")
    @ResponseWrapper(localName = "readStepsResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadStepsResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readStepsRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readStepsResponse")
    public String readSteps(
        @WebParam(name = "person", targetNamespace = "")
        Person person,
        @WebParam(name = "days", targetNamespace = "")
        int days);

    /**
     * 
     * @param person
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "idealWeight", targetNamespace = "")
    @RequestWrapper(localName = "updateIdealWeight", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.UpdateIdealWeight")
    @ResponseWrapper(localName = "updateIdealWeightResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.UpdateIdealWeightResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/updateIdealWeightRequest", output = "http://ws.controller_pc.ehealth/ServicePc/updateIdealWeightResponse")
    public String updateIdealWeight(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "weightChange", targetNamespace = "")
    @RequestWrapper(localName = "readBigWeightChange", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadBigWeightChange")
    @ResponseWrapper(localName = "readBigWeightChangeResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadBigWeightChangeResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readBigWeightChangeRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readBigWeightChangeResponse")
    public String readBigWeightChange(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "measureReminder", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureReminder", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadMeasureReminder")
    @ResponseWrapper(localName = "readMeasureReminderResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadMeasureReminderResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readMeasureReminderRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readMeasureReminderResponse")
    public String readMeasureReminder(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "goalReminder", targetNamespace = "")
    @RequestWrapper(localName = "readGoalReminder", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadGoalReminder")
    @ResponseWrapper(localName = "readGoalReminderResponse", targetNamespace = "http://ws.controller_pc.ehealth/", className = "ehealth.controller_pc.ws.ReadGoalReminderResponse")
    @Action(input = "http://ws.controller_pc.ehealth/ServicePc/readGoalReminderRequest", output = "http://ws.controller_pc.ehealth/ServicePc/readGoalReminderResponse")
    public String readGoalReminder(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

}
